var n;Array.prototype.includes||(Array.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);const aa=Boolean,ba=Array.isArray,t=RegExp.prototype.test,ca=RegExp.prototype.exec,da=Array.prototype.includes;Array.prototype.concat.bind([]);
const ea=Function.call.bind(Array.prototype.slice),fa=Function.apply.bind(Array.prototype.push),ha=Function.apply.bind(String.fromCharCode,null),w=Math.floor,x=Math.random,y="undefined"==typeof browser;y&&(browser=chrome);const z=navigator.userAgent.includes("Edge/"),ia=navigator.userAgent.includes("Edg/"),D=navigator.userAgent.includes("Firefox/"),ja=navigator.userAgent.includes("OPR/"),ka=navigator.userAgent.includes("YaBrowser/");var E=0,la,F,ma,pa,qa;const ra=D?69:z?77:66,sa=D?220:150,ta=browser.runtime.getManifest();
var ua=ta.permissions.includes("notifications")||null;const wa=va("tooltip_title"),xa=va("tooltip_disabled"),ya=va("tooltip_error"),za="\n"+va("tooltip_text"),Aa={16:"images/logo16.png",32:"images/logo32.png"},Ba={16:"images/logo16x.png",32:"images/logo32x.png"},Ca=["127.0.0.1:1001","0.1.0.1:1001"],Da=y?"Chrome_RenderWidgetHostHWND":D?"MozillaWindowClass":z?"Windows.UI.Core.CoreWindow":null,Ea=/(?!)/,Fa=["main_frame","sub_frame"],Ga=["object","image"];
var Ha=Ga.concat("xmlhttprequest",z?"other":[]),Ia=Fa.concat(Ga,"xmlhttprequest","other");const H=["*://*/*"],Ja=["ftp://*/*"],Ka=H.concat(Ja,"file:///*",y?"about:blank":[]),La=H.concat(y?"about:blank":[]),Ma=y&&btoa(x().toString().substr(2,9)),Na=browser.runtime.getURL("captured.html?"+(Ma?"auth="+Ma+"&":"")),Oa=browser.runtime.getURL("welcome.html?"+(Ma?"auth="+Ma+"&":"")),Pa=browser.runtime.getURL("").slice(0,-1),Qa=location.href,Ra=ja||ka,Sa=y||z,Ta=!D;var Ua=y;
const Va=t.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),Wa=t.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i),Xa=t.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|plain))$/),Ya=t.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),Za=t.bind(/^ftp:|^idmreg:|\bidman|\binternetdownloadmanager\b/i),$a=t.bind(/^[GPTSDVACR]*$/);ca.bind(/:\/\/.+\/([^/]+?(?:\.([^./]+?))?)(?=[?#]|$)/);
const ab=ca.bind(/\.([^.\\/]*?)(?:\.[0-9.]+)?$/),bb=ca.bind(/^v(\d+)\.(\d+)(?:b(\d+))?\b/),cb=da.bind([301,302,303,307,308]),db=da.bind([301,302,303]),eb=[],fb=t.bind(/^(?:https?|socks[45])$/),gb={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},hb=[null,[115,111,112,113,114],[111,112,114],[112],[111],[111],[111],[111]],ib=[null,[115,116,117,118,119,120,121,123],[114,113,113,115,116,117,118,122,119,121,124,125,120,123,112],[113],[111,101,113,112,114,115,116],[111,112,113],[],[111]],jb=
[null,2,2,null,2,null,null,2],kb={16:1,17:2,18:4,45:8,46:16},lb={http:1,https:9,ftp:2,ftps:10,idmreg:12,xup:33},mb={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS",
"application/json":"JSON","application/json+protobuf":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/ocsp-response":"OCSP","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/pkix-crl":"CRL","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX",
"application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC",
"application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8","video/mp4":"MP4|M4V|M4S","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD",
"video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4|M4S","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3",
"audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
function nb(a,b,c,d,e,f,h){if(a){var g=["MSG#",a,"#",b,"#",c,"#",d];this.j=a;this.type=b;this.o=c;this.l=d;this.a=e||[];this.h=g;if(e)for(a=0;a<e.length;a++)g.push(":",e[a]||0);if(f)for(var l in f)if(e=f[l],null!=e)if(g.push(",",l,"="),e instanceof Array){a=g.length;b=0;for(var k of e)b=k instanceof Uint8Array?b+(h?ob(k=ha(k)):k.length):b+ob(k=k.toString()),g.push(k);g.splice(a,0,b,":")}else"string"==typeof e||e instanceof String?g.push(ob(e),":",e):e instanceof Blob?g.push(e.size,":",e):g.push(e)}else this.i=
new FileReader}function pb(){this.a=pb.prototype.h++}pb.prototype.h=1;function qb(a,b,c,d){this.id=a;this.port=b;c&&(this.b=c=c.toLowerCase(),this.c="iframe"==c);d&&(this.f=d)}qb.prototype.a=0;function rb(a,b,c){this.id=a+","+b;this.c=null==c||0>c?null:a+","+c}function sb(){}function tb(a){a.f||(a.h.push(";"),a.f=!0);return a.h.join("")}function ub(a){a.f||(a.h.push(";"),a.f=!0);return new Blob(a.h)}function vb(a,b,c){a.f?a.c(a):(b.a=c||0,b.b=0,a.i.onload=a.s.bind(a,b),wb(a,b,0,50))}
nb.prototype.s=function(a){for(var b=this.i.result;;)switch(a.b){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.c(this);a.b=1}var f=e.length+1;d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.c(this);this.j=parseInt(d[1]);this.type=parseInt(d[2]);this.o=parseInt(d[3]);this.l=parseInt(d[4]);b=b.slice(f);a.a+=f;a.b++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return wb(this,a,b.length,100);a.b=
4}f=e.length+1;d=this.a=e.split(":");for(e=0;e<d.length;e++)c=d[e],d[e]=c.includes(".")?parseFloat(c):parseInt(c);b=b.slice(f);a.a+=f;a.b++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));d=c.shift().split(":",2);var h=d.shift();f=h.length;e=!1;if(d.length)f++;else{if(!c.length)return wb(this,a,b.length,25);e=!0}d=h.split("=",3);if(2!=d.length)return this.c(this);c=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[c]=d;b=b.slice(f);a.b++;break}a.f=c;a.c=d;b=a.c;f=a.a;a=a.slice(f,
f+b);a.size==b?this.i.readAsText(a):this.c(this);return;case 3:return this[a.f]=b,a.a+=a.c,a.b++,wb(this,a,0,21);case 4:switch(b[0]){case ",":a.b=2;b=b.slice(1);break;case ";":a.b++;break;default:return this.c(this)}a.a++;break;case 5:this.f=!0;this.g(this);a.size>a.a&&(b=new nb,b.g=this.g,b.c=this.c,vb(b,a,a.a));return}};function wb(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.i.readAsBinaryString(b.slice(e,c+d)):a.c(a)}
function K(){var a=this.constructor.prototype;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.Ea=[];this.na=this.A=null;this.o=!1;this.ua=this.Y=0;this.ia=null;this.c={};this.i={};this.a={};this.u={};this.b={};this.H={};this.f={};this.g={};this.X={};this.S={};this.h={};this.P={};this.V={};this.V.Wb=[];this.qa=ta.version||"";this.Sa="";this.da=0;this.va=!1;this.I=null;this.Ia=this.Ra=this.pa=this.l=!1;this.v=!D;this.Ta=this.Ja=!0;this.Ka=this.J=this.L=null;this.wa=this.W=
!1;this.Pa=!0;this.Xb=this.Qa=this.Vb=1;this.ta=this.j=this.M=null;this.xa=1;this.Va=0;this.G=this.C=null;this.La=Ea;this.K=[];this.O=this.s=null;this.ea=Array(16);this.sa=0;this.Ma=null;this.Aa=this.ra=!1;for(a=1;a<hb.length;a++){var b=this.K[a]={};for(var c of hb[a])b[c]=Ea}browser.browserAction&&(L(this,!1),browser.browserAction.setBadgeBackgroundColor({color:"#606060"}),browser.browserAction.onClicked.addListener(this.jb));D&&1056964608<=E&&browser.contextMenus.onShown.addListener(this.kb);D&&
browser.runtime.onInstalled.addListener(this.ob);browser.runtime.onMessage.addListener(this.pb);browser.windows.onCreated.addListener(this.ab);browser.windows.onRemoved.addListener(this.bb);browser.windows.onFocusChanged.addListener(this.Qb);browser.windows.onBoundsChanged&&browser.windows.onBoundsChanged.addListener(this.Pb);browser.tabs.onActivated.addListener(this.Gb);browser.tabs.onUpdated.addListener(this.Jb);browser.tabs.onRemoved.addListener(this.Ib);browser.tabs.onAttached&&browser.tabs.onAttached.addListener(this.Hb);
y&&1056964608<=E&&browser.webRequest.onBeforeRequest.addListener(this.lb,{urls:[browser.runtime.getURL("*")]},["blocking"]);this.Yb();this.cb()}function xb(){}xb.prototype=[];var M=xb.prototype;xb=null;n=K.prototype;n.kb=function(a,b){yb(this,b.id,!0,!1,!0)};n.ob=function(a){this.qa=a.version=ta.version;this.Sb=a};function zb(a,b){b&&browser.storage.local.set({consent:a.qa});a.J=null;a.ya(5);a.v=!0;Ab(a)}
n.pb=function(a,b){switch(a[0]){case 38:browser.tabs.remove(b.tab.id);break;case 42:zb(this,!0);break;case 43:browser.management.uninstallSelf({showConfirmDialog:!0})}};n.jb=function(a){if(this.wa){if(this.J)return browser.windows.update(this.J,{focused:!0});var b=a.id,c=this.h[b];L(this,c,b,!0);this.W&&(c?(this.ca(a.windowId),Bb(this,b)):Cb(this,b))}};
function L(a,b,c,d){var e=b,f=d;c?(a.h[c]=!b,b||(f=!0)):(a.wa=b||d,f=!0,D&&(a.wa?browser.browserAction.enable():browser.browserAction.disable(),e=!0));if(f){a=b?wa+za:c?xa+za:d?xa:ya;d=e?Aa:Ba;f=c&&D&&989855744<=E;if(y&&822083584>E||z)d=d[16];z||browser.browserAction.setTitle({title:b&&f?null:a,tabId:c});browser.browserAction.setIcon({path:e&&f?null:d,tabId:c});browser.browserAction.setBadgeText({text:b?f?null:"":"X",tabId:c})}}
function Ab(a){var b=a.c,c=a.P={};browser.contextMenus.removeAll();for(var d=0;d<Db.length;d++){var e=Db[d];e[0]&&b[e[1]]&&(c[d]=browser.contextMenus.create({title:va(e[2]),contexts:e[3].split(","),onclick:e[4].bind(a),documentUrlPatterns:e[5]||Ka,enabled:!0}))}a.W||(a.W=!0,L(a,!0),a.D(1,browser.runtime.onConnect,a.Bb),y&&a.D(1,browser.proxy.settings.onChange,a.Za),y&&browser.proxy.settings.get({},a.Za),a.D(1,browser.webNavigation.onCreatedNavigationTarget,a.zb),a.D(1,browser.webNavigation.onCommitted,
a.Ya),a.D(1,browser.webNavigation.onHistoryStateUpdated,a.rb),(b=a.c[17])&&a.D(2,browser.webRequest.onBeforeRequest,a.Kb,{urls:b.split("|"),types:Fa},["blocking"]),Eb(a,!0),browser.tabs.query({url:H},a.la))}
function Eb(a,b){y&&a.l&&browser.downloads.setShelfEnabled(!b);if(b){y&&a.l&&a.D(3,browser.downloads.onCreated,a.mb);y&&a.l&&a.D(3,browser.downloads.onDeterminingFilename,a.nb);b=pa?void 0:Ia;const c=["blocking"],d=y&&!qa&&1207959552<=E?["extraHeaders"]:[];a.D(4,browser.webRequest.onBeforeRequest,a.$a,{urls:Ja,types:Fa},c);a.D(4,browser.webRequest.onBeforeRequest,a.$a,{urls:H,types:b},["requestBody"]);a.D(4,browser.webRequest.onBeforeSendHeaders,a.Lb,{urls:H,types:b},["requestHeaders"].concat(c,d));
a.D(4,browser.webRequest.onHeadersReceived,a.Nb,{urls:H,types:b},["responseHeaders"].concat(c));a.D(4,browser.webRequest.onResponseStarted,a.Ob,{urls:H,types:b});a.D(4,browser.webRequest.onErrorOccurred,a.Mb,{urls:H,types:b})}else a.ya(3,4)}
n.Za=function(a){browser.runtime.lastError;if(a){var b=a.value;a=gb[b.mode];var c,d;this.ea.fill(void 0);if(5==a&&(d=b.pacScript))d.data&&5E4<d.data.length?a=4:(c=d.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=d.url,this.ea.fill(!0);else if(7==a){b=b.rules;d=b.bypassList;c=Fb(this,b.singleProxy);if(!c){c=Fb(this,b.fallbackProxy);var e=Fb(this,b.proxyForHttp,1),f=Fb(this,b.proxyForHttps,9);b=Fb(this,b.proxyForFtp,2);e!=f||e!=b||e!=c&&c?(c=(e||"")+";"+(f||
"")+";"+(b||"")+";"+(c||""),++a):c=e}d&&d.length&&(c+=";"+d.join(","))}b=5>a?a.toString():c?a+":"+c:null;b!=this.s&&(this.s&&this.Ga(),this.s=b)}};function Fb(a,b,c){if(b){var d=b.scheme||"http",e="https"==d;a=a.ea;c?a[c]=e:a.fill(e);if(fb(d))return d+"://"+b.host+(b.port?":"+b.port:"")}}
function Gb(a,b,c,d){if(b){var e=b.type;if("direct"==e)return"0";"socks"==e&&(e="socks5");if(fb(e)){var f="1:"+e+"://"+b.host+":"+b.port;"socks5"==e&&b.proxyDNS&&(f+="#");c||d||!(c=a.O)||(c=c.substr(c.indexOf(";")+1||c.length));c&&(f+=";"+c);d&&f&&(a.O=f);return f}}}
n.Ga=M[M.length]=function Hb(a,b){if(void 0===a){if((Ta||Ua)&&this.o){var d=this.C;d||(b="http://"+(this.A?(new URL(this.A.url)).host:Ca[0]),d=b+"/status/204+IDM");a=new XMLHttpRequest;a.timeout=1E3;a.onreadystatechange=Hb.bind(this,a,b);a.open("GET",d,!0);a.send()}}else 4==a.readyState&&(204!=a.status?this.C=this.G=null:b&&(this.C=b+"/status/204+IDM",this.G=Ta&&this.ia?b+"/client/"+this.ia:null))};n.oa=function(a,b,c,d){var e=this.f;return b in e?e[b]:e[b]=new qb(b,a,c,d)};
function Ib(a,b){a=a.g;var c=b.id;a[c]!==b&&(a[c]=b,z&&(a[b.requestId]=b))}function Jb(a,b,c,d,e){if(N(b)){var f=b.frameId||0;var h=b.parentFrameId;var g=b.method&&b.id;d||(d=b.tabId);e||(e=b.url)}else f=b;var l=a.u[d+","+f];l||(l=new rb(d,f,h),a.u[l.id]=l);g?(l.g!=g&&(l.g=g,l.j=e,l.f=!1,l.b&&(l.b=e.startsWith(b.initiator||b.originUrl))),l.h="POST"==b.method):e&&(e.startsWith("about:blank")?f&&(l.b=!0):l.m=e);null!=c&&(l.refresh=c);return l}function Kb(a,b){return a.u[b.tabId+","+b.frameId]}
function Lb(a){var b=new pb;return a.H[b.a]=b}function Ob(a,b){delete a.H[b instanceof pb?b.a:b]}function Pb(a,b){a=a.K;for(var c=1;c<a.length;c++){var d=a[c][101];if(d&&d.test(b))return c}return 0}
n.za=function(){var a=this.Y%(Ca.length+1);if(a<Ca.length){a=Ca[a];var b=x().toString().substr(2,9);this.A=a=new WebSocket("ws://"+a+"/?cid="+b,"plugin.v3.internetdownloadmanager.com");a.onopen=this.Ca;a.onclose=this.R;a.onmessage=this.Fb;a.onerror=O;1==a.readyState?this.Ca():3==a.readyState?this.R():a.timeout=window.setTimeout(this.R,1500,a)}else if(z)this.R();else{this.na=a=browser.runtime.connectNative("com.tonec.idm");try{a.postMessage("")}catch(c){a=null}a?(a.onDisconnect.addListener(this.R),
a.onMessage.addListener(this.sb),this.Ca()):this.R()}};n.Ca=function(){this.o=!0;this.Qa=1;var a=this.A;a&&a.timeout&&(window.clearTimeout(a.timeout),a.timeout=null);a=browser.i18n.getUILanguage().replace("_","-");"sr"==a&&(a+="-Cyrl-CS");var b=[16,49,Ra?1028:1031,0],c={};c[112]=F;c[113]=la;c[114]=Da;c[125]=JSON.stringify(this.Sb);c[116]=a;P(this,2,1,Ra?0:1024,b,c)};
n.R=function(a){browser.runtime.lastError;var b=a.target||a;if(b instanceof WebSocket&&(b.timeout&&(window.clearTimeout(b.timeout),b.timeout=null),a===b))return b.close();this.A=this.na=null;this.o&&(this.o=!1,this.X={},Eb(this,!1),this.ya(1,2),this.W=!1,this.s=this.G=this.C=null,L(this,!1));a=++this.Y;b=Ca.length+1;var c=a/b;120>c&&(1==c&&Qb(this),!a||a%b?this.za():window.setTimeout(this.za,5E3*c))};n.Fb=function(a){var b=new nb;b.g=this.Xa;b.c=this.R;vb(b,a.data)};
n.sb=function(a){var b=new nb;b.g=this.Xa;b.c=this.R;vb(b,new Blob([a]))};function P(a,b,c,d,e,f,h){if(!a.o)return!1;var g=a.Qa++;b=new nb(g,b,c,d,e,f,!a.A);if(h)return h.open("POST",a.G+"?seq="+g,!1),h.send(ub(b)),200==h.status;if(h=a.A)h.send(ub(b));else try{a.na.postMessage(tb(b))}catch(l){return a.R(),!1}d&1&&(a.X[g]=b);return!0}
function Rb(a,b){if(b.a){var c=b.a[1]||b.a[6],d=a.g[c];if(d)return d.c?b.b=d.port.id:null;d=a.i;for(var e in d)if(d[e].f==c)return b.b=e}e=b[6];d=b[17];var f=b[50],h=b[7],g=a.V,l=a.f;a=a.a;var k;if((k=g[e])||(k=g[d]))return b.b=k.id;if(k=g[f])var m=k.id;for(c in l){g=l[c];var p=g.f;if(p){if(p==e||p==d||p==f){k=g.port;if(h){var q=a[k.tabId];q&&q.m!=h&&(k=null)}if(k)return b.b=k.id}if(p==h)var r=g.port.id}}return m?b.b=m:r?b.b=r:null}
n.gb=M[M.length]=function Sb(a,b,c,d){var f;a:for(;!c;){if(f=a.b)return f;if(a.a){var h=this.a[a.a[6]+","+a.a[7]];h?f=h.id:(h=a.a[7])&&this.i[h]&&(f=h)}if(f||(f=Rb(this,a)))break;var g=this.i,l=a[50],k=a[7],m;for(m in g){h=g[m];if(h.m==l){f=m;break a}h.m==k&&(f=m)}if(f)break;return k?browser.tabs.query({url:k},Sb.bind(this,a,b,!0)):null}return c?(browser.runtime.lastError,d&&(d=d.shift())&&(h=this.a[d.id])&&(f=a.b=h.id),b&&b(f)):a.b=f};
n.Na=M[M.length]=function Tb(a,b,c){var e=a.tabId,f=a.$;if(b)if(ba(c))for(var h=a.m,g=h.includes("#")&&Ub(h),l=c.length;l--;){b=c[l];var k=b.frameId;if(k!=f)if(k&&!b.lc&&(b.url==h||g&&b.url==g))f=a.$=k;else continue;var m=b.parentFrameId;break}else c?m=c.parentFrameId:browser.runtime.lastError;else if(0<f?!a.c:null==f){if(f&&822083584<=E)return browser.webNavigation.getFrame({frameId:f,tabId:e},Tb.bind(this,a,!0));if(f||a.m)return browser.webNavigation.getAllFrames({tabId:e},Tb.bind(this,a,!0))}0<=
m&&(a.c=e+","+m);if(null!=f&&a.h){if(b=this.u[e+","+f])a.f=b.g,a.i=b.f,a.refresh=b.refresh,a.o=b.b,(c=b.aa)&&a.m!=c&&(a.aa=c),a.c||(a.c=b.c),(c=this.g[a.f])&&!c.port&&(c.port=a);this.a[e+","+f]=a;m=this.pa?1:null;c=a.j;e=[11,a.id,e,f,c,a.refresh,a.i,m&&eb[m]];c&&a.i&&(f=this.K[c],m=jb[c],c=ib[c],e.push(m&&eb[m]),fa(e,c.map(Vb(f)).map(Wb)));a.postMessage(e)}};
n.ha=M[M.length]=function Xb(a,b,c,d,e,f,h,g){var k=Yb(a);if(!k)return 0;var m=0<(k&32),p=1==(k&=7);if(p&&!m){if(!h)return Q(a,Xb.bind(this,a,b,c,d,e,f,!0)),-1;N(g)&&(g=R(g))}h=[k];k={};k[6]=Ub(a,p,this);k[50]=b;k[7]=c;k[8]=d;k[100]=e;k[102]=f;k[51]=g;k[54]=navigator.userAgent;k[121]=D?this.O:this.s;P(this,14,1,0,h,k);return 3};
n.Zb=M[M.length]=function Zb(a,b,c,d,e,f){if(c){var g=c.c;var l=c.M;var k=c.l}if(!d){if(!a||!a.length)return;f=$b();g&&!l&&Q(g,e=S());for(var m of a)Q(m[0],f[f.length]=S());return T(Zb,this,a,b,c,!0,e,f)}e&&(l=R(e));for(m of a)m[5]=R(f.shift());b=0;c=[0];d={8:4};d[54]=navigator.userAgent;d[7]=g;d[110]=k;d[111]=l;d[121]=D?this.O:this.s;1<a.length&&(P(this,15,1,0,[a.length],d),b=16,d={});for(m of a)d[6]=m[0],d[100]=m[2],d[102]=m[3],d[50]=m[4],d[51]=m[5],P(this,14,1,b,c,d)};
function yb(a,b,c,d,e,f,h,g,l){if(!d||a.c[-8]){var k=a.a[b];if(k){var m=Lb(a);m.tabId=b;m.port=k;m.C=c;m.H=e;m.b=0;m.f=[];if(k=d&&!!f)m.I=!0,m.K=f,m.u=h,m.v=g,m.s=l,f.b||ac(a,f);f=m.a;(d=d&&a.c[12])?(d=d.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),d="^(?:http|https|ftp|ftps)://(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)"):d="^(?:http|https|ftp|ftps)://";m.g=bc(a,b,[12,f,c,k||e,d]);m.A=0;m.g||Ob(a,m)}}}
n.Tb=function(a,b,c,d,e,f,h,g){if(a=this.H[b]){d&&(a.b+=d);h&&(a.c=h);g&&(a.l=g);if(e&&("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array)){if(f)for(var l of e)l[4]=f;fa(a.f,e)}++a.A<a.g||(a.I?(d=a.tabId,(e=this.b[a.port.a])&&e.B==d&&a.b&&(f=a.s,h=e.a,g=e.b,P(this,10,1,0,[4294967295,e.l,Math.round(a.u*f+(e.h+h)*g),Math.round(a.v*f+(e.A+h)*g),0,a.b]),this.j=d,bc(this,d,[13,!0]))):a.H?(d=0<a.b,this.Pa!=d&&(this.Pa=d,browser.contextMenus.update(this.P[2],{visible:d}),browser.contextMenus.refresh())):
(d=a.f,d.length?this.Zb(d,a.C,a):cc(a.tabId,"cannot_find_links")),Ob(this,a))}};n.xb=function(a,b,c,d){if(a=this.H[b])this.ha(a.j,a.o,a.c,a.i,c,d),Ob(this,a)};n.Ab=function(a,b,c,d,e,f){this.oa(a,b,c,d);a=[b,a.tabId,a.f,a.j];b={};b[132]=d;b[134]=e;b[133]=f;P(this,23,1,0,a,b)};
n.Z=M[M.length]=function dc(a,b,c){if(4294967295==a)this.j=null,c=!0;else{var e=this.f[a];if(e){c=e.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:e.a=3;window.setTimeout(dc.bind(this),1E3,a,!1,!0);return}e.a=0;c=!0}}c&&P(this,8,1,32,[a])};
n.ec=function(a,b,c,d,e,f,h,g,l){var k=a.tabId,m=a.a,p=this.b[m],q=this.h[k];if(b){var r=this.H[b],u=r&&r.G;if(u){if(!c&&a.o){var A=this.a[a.c];if(A)return A.postMessage([15,b,null,u[6],u[17],u[50],u[31],u[133]])}var B;if(!d){if(!c||null==e){if(!a.b){c=a.ja;f="iframe";h=a.m;var v=!!c}if(!v){c=k;f=h=null;var C=!0}}a=this.oa(a,c,f,h);p=k==p.B&&!p.N&&(C||v||e)&&!q;!p||C||a.a||window.setTimeout(this.ca,3E3,m);var I=2;a.a=p?1:2;var J=(p?128:64)|(C?512:0);!g&&(B=this.a[k])&&(g=B.s)}U(this,u,I||1,J||0,m,
k,c,g,l);!I||C||q||ec(this,c,e);Ob(this,r)}}else d?(this.Z(c,!0),delete this.f[c]):k!=p.B||p.N||q||(e?ec(this,c,e,!0):fc(this,c))};function gc(a,b){var c=a.b[b];if(c&&c.fa){var d=c.a,e=c.b;P(a,7,2,c.N?128:c.o?256:c.g?512:0,[b,Math.round((c.h+d)*e),Math.round((c.A+d)*e),Math.round((c.width-d-c.s)*e),Math.round((c.height-d)*e)])}}
function ec(a,b,c,d){var e=a.f[b];if(e&&e.a){var f=e.port,h,g=256;2==e.a&&(null==d&&(h=a.b[f.a])&&(d=f.tabId==h.B&&!h.N),d?(g|=128,e.a=1):g|=64);(d=e.c)&&!c&&(c=f.g);if(c){var l=c[0];var k=c[1];var m=c[2]||l+1;var p=c[3]||k+1;var q=c[4];if(c=!d&&f.g)l+=c[0],k+=c[1],m=Math.min(m+c[0],c[2]),p=Math.min(p+c[1],c[3]);if(f=a.a[f.tabId])var r=f.v}P(a,9,1,g,[b,l,k,m,p,q,r])}}
n.ca=function(a){var b=this.h,c=this.a,d=this.b,e=a?[d[a]]:V(d);a=[];d={};for(var f of e)!f||f.N||f.ba||b[f.B]||a.push(f.B);if(a.length)for(var h of V(this.f))h.a&&(b=h.port,f=b.tabId,a.includes(f)&&((f=b.b?b:c[f])&&f.update&&(f.update=!1,f.postMessage([14,!1])),h.b?b.b?b.postMessage([15,null,h.id]):ac(this,b,null,d):ec(this,h.id,null,!0)))};function hc(a,b){var c=a.b,d;if(b=null==b?V(c):(d=c[b])?[d]:null)for(d of b)Cb(a,d.B,void 0)}
function Cb(a,b,c,d){d=0!=d;var e=c?0:2;c=c?32:64;var f=a.f,h;for(h in f){var g=f[h];g.a&&g.port.tabId==b&&g.a!=e&&(d||g.b)&&(g.a=e,P(a,8,1,c,[h]))}}function fc(a,b){var c=a.f[b];c&&1==c.a&&(c.a=2,P(a,8,1,64,[b]))}function ic(a,b,c,d){var e=a.sa,f=(e&b)!=((c?255:128)&b);a.sa=c?e|=b:e&=~b;f&&(c=a.c[-1],b=a.c[-2],c=a.ra=0!=c&&(e&c)==c,e=a.Aa=0!=b&&(e&b)==b,a.Ma=(c||e)&&d||null)}
n.Da=M[M.length]=function jc(a,b,c,d,e){var h=this.b[a];if(h)if(h.ba?d&&(window.clearTimeout(h.ba),h.ba=null):d||(d=-1),0<=d)h.i|=b,h.j|=c,d&&(h.ba=window.setTimeout(jc.bind(this),d,a));else{b|=h.i;c|=h.j;h.i=h.j=h.ba=null;if(b){for(var g of V(this.i))g.b&&g.a==a&&(g.update=!0);e?this.U(e):browser.windows.get(a,this.U);browser.tabs.query({windowId:a,active:!0},this.U)}if(c){if((a=this.b[a])&&!a.N&&!a.ba&&(a=a.B,!this.h[a])){b=this.f;for(var l in b)c=b[l],c.a&&c.port.tabId==a&&1==c.a&&P(this,8,1,1152,
[l])}}else this.ca(a)}};
n.U=M[M.length]=function kc(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var d=a.windowId||a.id,e=this.b[d];if(e){var f=!a.windowId;if(f){var h=b?e.b=this.xa:e.b,g=e.g="minimized"==a.state,l=e.o="maximized"==a.state;g||(z?(e.width=Math.round(a.width/h),e.height=Math.round(a.height/h),e.c=Math.round(a.left/h),e.f=Math.round(a.top/h)):(e.width=a.width,e.height=a.height,e.c=a.left,e.f=a.top),g=e.N,a=e.N="fullscreen"==a.state,h=l&&-e.c,0<h&&16>=h&&h==-e.f&&(e.a=h),a==g||b||(a?
hc(this,d):this.ca(d)))}else{if(e.C&&Va(a.url))return;a.width&&(e.v=a.width);a.height&&(e.u=a.height)}if(!e.g){h=e.width;g=e.v;l=e.height;a=e.u;var k=g>h||a>l;if(k||!g||!a){f||k&&browser.windows.get(d,kc.bind(this));return}f=h-g;h=f/2;0<=h&&16>=h?(e.a=h,e.h=e.s=0):(h=e.a,D||ja?e.h=f-2*h:e.s=f-2*h);f=l-a-2*h;f>=(e.G?20:50)&&f<=sa&&(e.A=f);e.C=!0}b||gc(this,d);return e}}};function Bb(a,b){return a.h[b]?!0:(a=a.a[b])&&a.refresh?(a.refresh=!1,browser.tabs.reload(b),!0):!1}
n.bc=function(a,b,c,d){a.m=b;a.u=c;a.refresh&&!d&&(a.refresh=!1);null==a.$&&this.Na(a);this.ca(a.a);a.b&&0<this.I&&lc(this)};n.dc=function(a,b,c,d,e){a.s=b;a.v=e;a=[a.f,a.tabId,a.a,d,e];d={};d[110]=b;d[128]=c;P(this,21,1,0,a,d)};
n.fc=function(a,b,c,d,e){var f=a.tabId,h=this.a[f+","+c];if(h){var g=h.g;h.ja=d;if(h.g=e){var l=a.g;l&&(e[0]+=l[0],e[1]+=l[1],e[2]=Math.min(e[2]+l[0],l[2]),e[3]=Math.min(e[3]+l[1],l[3]));if(g&&g.join()!=e.join()){g=this.a;a=a.tabId+",";c=a+c;for(var k in g)k.startsWith(a)&&(l=g[k],l.c==c&&h.postMessage([16,b,l.$,l.ja]))}}if(!this.h[f]){ec(this,d,e);for(var m of V(this.f))m.port==h&&m.a&&m.b&&!m.c&&h.postMessage([15,null,m.id])}}};
function ac(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.c];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.ja,c[2]=b.$,c[3]=d,c[4]=d?null:b.m,c[5]=d?null:b.aa,f.postMessage(c)}function bc(a,b,c){a=a.a;b+=",";var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}
n.la=function(a,b){var c={file:"content.js",runAt:"document_start",matchAboutBlank:!0};b&&!z?c.frameId=b:c.allFrames=!0;if(a instanceof Array)for(;b=a.shift();)try{b.discarded||browser.tabs.executeScript(b.id,c,O)}catch(d){}else if(b=a)try{browser.tabs.executeScript(b.id||b,c,O)}catch(d){}};function mc(a,b,c,d){null==c&&(c=b.l==a.M);c=17|(c?2048:1024)|(b.o?256:b.g?512:0);b=[b.l,b.fa,b.width,b.height,b.c,b.f,b.b];var e={};e[117]=d;P(a,6,2,c,b,e)}
n.cb=M[M.length]=function nc(a,b,c){if(b){a={};for(var e of c)a[e.windowId]=e;for(var f of b)e=a[f.id],b=this.U(f,!0)||this.ab(f,!0,e),mc(this,b,f.focused,f.title||e&&e.title)}else{if(!a){try{browser.windows.getAll({windowTypes:["normal","popup"]},b=S())}catch(h){browser.windows.getAll(b)}browser.tabs.query({active:!0},c=S());return T(nc,this,1,b,c)}if(z&&1==a&&c){b=$b();for(f of c)browser.windows.get(f.windowId,b[b.length]=S());return T(nc,this,2,b,c)}}};
n.ac=M[M.length]=function oc(a,b){if(void 0===a)return pc("system.display",oc.bind(this));if(a){if(!b)return browser.system.display.getInfo(null,oc.bind(this,a));this.Va=b[0].displayZoomFactor}};
n.Ba=function(a,b){if(!this.o)return cc(b.id,"cannot_contact_idm");var c=a.linkUrl,d=a.pageUrl,e=d;if(a.menuItemId==this.P[4])return browser.downloads.search({query:[c]},this.fb.bind(this,c));if(a.menuItemId==this.P[1])c=a.frameUrl,c&&"about:blank"!=c||(c=d,e=null);else if(!c&&(c=a.srcUrl,(a=this.a[b.id+","+a.frameId])&&c)){var f=Lb(this);f.tabId=b.id;f.port=a;f.j=c;f.o=e;f.c=d;f.i=4;return a.postMessage([18,f.a,c])}c&&this.ha(c,e,d,4)};
n.Ha=function(a,b){if(!this.o)return cc(b.id,"cannot_contact_idm");yb(this,b.id,a.menuItemId==this.P[2])};n.fb=function(a,b){for(var c,d,e;c=b.pop();)c.exists&&"complete"==c.state?d||e||(e=c.referrer):(d||(d=c.referrer),browser.downloads.erase({id:c.id}));this.ha(a,d||e,null,4)};
n.Bb=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=this.Vb++);var d=b.id,e="top"==a.name;a.tabId=d;a.a=0>b.index?null:b.windowId;a.h=!0;a.l=!1;a.update=e;a.b=e;a.$=e?0:a.sender.frameId;a.A=0;a.m=a.sender.url||e&&b.url||null;a.aa=null;this.i[c]=a;e&&(this.a[d]=a);a.m&&(a.j=Pb(this,(new URL(a.m)).hostname));a.onMessage.addListener(this.Cb.bind(this,a));a.onDisconnect.addListener(this.ma);this.Na(a)}};
n.ma=function(a,b){browser.runtime.lastError;if(a.h){a.h=!1;var c=a.tabId+","+a.$,d=this.H,e=this.f,f,h=this.V,g=this.g,l,k;for(k in d)d[k].port===a&&delete d[k];for(k in e)if(f=e[k],f.port===a)this.Z(k),delete e[k];for(var m in h)h[m]===a&&delete h[m];for(k in g)(l=g[k],l.port!==a||l.g)||delete g[k];this.Ma===a&&ic(this,255,!1);delete this.i[a.id];delete this.a[c];a.b&&delete this.a[a.tabId];if(z&&!b)browser.tabs.executeScript(a.tabId,{code:"__idm_connect__ && __idm_connect__(); true;"},O);else for(k in a=
this.u,a)c==a[k].c&&delete a[k]}};
n.Cb=function(a,b){var c=b[0];b[0]=a;switch(c){case 21:this.bc.apply(this,b);break;case 24:this.dc.apply(this,b);break;case 22:this.fc.apply(this,b);break;case 23:this.ec.apply(this,b);break;case 41:this.Ab.apply(this,b);break;case 25:this.oa.apply(this,b);break;case 26:yb(this,a.tabId,!0,!0,!1,a,b[1],b[2],b[3]);break;case 27:this.Tb.apply(this,b);break;case 28:this.Z(4294967295);break;case 29:this.Wa.apply(this,b);break;case 30:this.Wa.apply(this,b);break;case 31:this.vb.apply(this,b);break;case 32:this.yb.apply(this,
b);break;case 39:this.wb.apply(this,b);break;case 33:this.qb.apply(this,b);break;case 34:this.ub.apply(this,b);break;case 35:this.xb.apply(this,b);break;case 36:this.Rb.apply(this,b);break;case 37:this.Eb.apply(this,b)}};
n.Xa=function(a){var b=a.type,c=a.o,d=a.l,e=a.a,f;if(1==b){var h=e[0];if(f=this.X[h])b=f.type,delete this.X[h]}switch(b){case 3:0<=this.Y&&(this.Y=-1,this.Ga());d=this.ua=e[0];this.Ra=9>d;this.Ia=10<=d;this.ia=e[6];if(d=e[4])d/=96,this.xa=y&&1.245>d?1:d,this.cb(),y&&this.Va&&this.ac();qc(this,e[5],a);rc(this,!0);Qb(this);break;case 4:f=this.c;this.l=!!(e[3]&2147483648);this.pa=!!(e[3]&1073741824);qc(this,e[2],a);rc(this);f[-9]=0<(d&64);f[-13]=0<(d&1024)||Ra;f[-8]=0<(d&32);f[-4]=0<(d&2);f[-11]=0<(d&
256)||2>c;f[-12]=0<(d&512)||2>c;f[-1]=e[0];f[-2]=e[1];f[12]=a[12];f[17]=a[17];W(f,a,1);W(f,a,2);W(f,a,3);W(f,a,4);W(f,a,10);W(f,a,9,2);W(f,a,11,2);W(f,a,20);W(f,a,21,1);sc(f,a,19);sc(f,a,18,1,1);(this.v||this.Ja)&&Ab(this);break;case 18:d=e[0];if(7<d)break;f=hb[d];e=this.K[d];for(var g in a)(g=parseInt(g))&&(102==g||110<g&&150>g)&&(e[g]=f.includes(g)?RegExp(a[g]):a[g]);15>this.ua&&2==d&&(e[124]="a:not([target])",e[125]="<div >:not(:only-child):not(video:first-child,img:first-child:nth-last-child(2))",
e[120]=4);d=this.K.map(tc(102)).filter(aa);this.La=RegExp("^https?://(?:"+d.join("|")+")","i");W(e,a,101,2);break;case 5:a=e[0];(e=this.b[a])?(d=0!=(d&128),e.N!=d&&(e.N=d)&&hc(this,a)):this.bb(a);break;case 6:if(d&4)break;a=f.a[0];e=e[1];if(d=this.b[a])d.fa=e,gc(this,a);break;case 8:a=e[0];e=d&32;if(4294967295==a)bc(this,this.j,[13,!1]),this.j=null;else if(a=this.f[a])a.a=e?0:2;break;case 11:a=e[0];4294967295==a&&(yb(this,this.j,!0,!0),this.j=null);break;case 12:try{var l=a.a[5],k=a[4];e=4==l?2:3;
if(1==l||2==l){if(Rb(this,a)){if(this.c[3].test(k))1==l?e=6:l=4;else if(this.c[-4]||this.c[4].test(k))e=6;a[8]|=256}if(3==e){var m=this.b[this.M];m&&this.h[m.B]&&(e=1)}}if(4==l)if(!this.Ra||a.a[6]||a.a[7]){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.Ub(a)}else U(this,a,1);else U(this,a,e)}catch(p){U(this,a,0)}break;case 13:a=f.a[0];d=f.a[5];e=e[1];g=3==e;if(3>=d)f.l&128?uc(this,a,g):X(this,a,g);else if(5==d)if(e){if(a=(f=this.g[a])&&f.i){g=f.method;
e=f.requestHeaders;if(d=f.f)(d=vc(d,Y(e,"Content-Type")))||(g="GET");a.timeout=1E4;a.onreadystatechange=this.Db.bind(this,a,f.id);a.open(g,f.url,!0);for(f=0;f<e.length;f++)g=e[f].name,c=g.toLowerCase(),c.startsWith("x-idm-")||(Wa(c)&&(g="X-IDM-"+g),a.setRequestHeader(g,e[f].value));a.send(d)}}else wc(this,a);break;case 20:e=a[123];d=!e;a=[a.j,0,0,0];f={};D&&(g=this.O)&&(f[122]=g,d||(d=g.substr(2).split(";",1).shift()==e));f[121]=this.s;P(this,1,1,d?2:4,a,f);break;case 22:this.eb(e[0],e[1],a[131],
a[130]);break;case 1:break;default:!f&&d&1&&P(this,1,1,0,[a.j,0,0,0])}};n.eb=M[M.length]=function xc(a,b,c,d,e){if(!z&&null==ua){if(void 0===e)return pc("notifications",xc.bind(this,a,b,c,d));ua=e||!1}ua&&(browser.notifications.create(a.toString(),{type:"basic",title:d||"",message:c,iconUrl:"images/logoSmall.png"},O),b&&window.setTimeout(browser.notifications.clear,1E3*b,a.toString(),O))};
n.Ub=M[M.length]=function yc(a,b,c,d){try{var f=a.b;if(!f)if(c)f=a.b=c;else if(d){var h=this.b[d.id],g=this.a[h&&h.B];g&&(f=a.b=g.id)}else if(!b&&(f=this.gb(a,c=S()),!f))return browser.windows.getLastFocused(d=S()),T(yc,this,a,!0,c,d);var l=this.i[f];if(!l)return U(this,a,0);h=this.b[l.a];if(!h||!h.fa)return U(this,a,1);(g=this.a[l.tabId])&&g.update&&(g.update=!1,g.postMessage([14,!0]));var k=Lb(this),m=a.a[8],p=[15,k.a,m];k.G=a;m||(l.b||ac(this,l,k.a),p.push(a[6],a[17],a[50],a[31],a[133]));l.postMessage(p)}catch(q){U(this,
a,0)}};function U(a,b,c,d,e,f,h,g,l){-1!=c&&(e=[b.j,c,e,h,f],f={},f[8]=b[8],g&&(f[101]=g,f[128]=l),P(a,1,2,d|(0==c?4:2),e,f))}n.zb=function(a){Jb(this,a).a=!0;D&&browser.windows.get(a.windowId,this.U)};
n.Ya=function(a,b){var c=a.tabId,d=a.frameId,e=a.url,f=a.transitionType,h=f?f.endsWith("_subframe"):z&&0<d,g=this.u[c+","+d];this.L!=c||Va(e)||(this.L=null);!h&&this.h[c]&&(g?(f=g.i,f=!(e&&f&&(new URL(e)).hostname==(new URL(f)).hostname)):f=!0,L(this,f,c));g&&(g.i=e);if(f=this.a[c+","+d])if(this.j&&(a=this.b[f.a])&&a.B==this.j&&this.Z(4294967295),b){if(b=f.m,c=new URL(b),d=new URL(e),(c.origin!=d.origin||c.pathname!=d.pathname||1!=Pb(this,c.hostname)||"/watch"!=c.pathname||c.a("v")!=d.a("v"))&&e!=
b){b=this.f;var l,k;for(k in b)if(l=b[k],l.port===f)2==f.j?fc(this,k):(this.Z(k),delete b[k]);f.A++;f.m=e;f.b&&(f.update=!0);f.postMessage([17,!0])}}else this.ma(f,!0),h&&"about:blank"==f.m&&this.la(c,d);else h&&"about:blank"==e?(Jb(this,a),this.la(c,d)):g&&g.a&&(g.m||!b)&&(g.a=!1)};n.rb=function(a){return this.Ya(a,!0)};
n.ab=function(a,b,c){var d=a.id;c={l:d,width:a.width,height:a.height,c:a.left,f:a.top,b:this.xa,a:8,A:ra,h:0,s:0,G:"popup"==a.type,N:"fullscreen"==a.state,o:"maximized"==a.state,g:"minimized"==a.state,B:c&&c.id,u:c&&c.height,v:c&&c.width,C:!D,fa:null,ba:null};Object.setPrototypeOf(c,sb.prototype);this.b[d]=c;a.focused&&(this.M=d);b&&(browser.tabs.query({windowId:d,active:!0},this.U),browser.tabs.query({windowId:d,url:H},this.cc),browser.tabs.query({windowId:d,url:H},this.la));return c};
n.cc=function(a){for(var b of a)Jb(this,0,!0,b.id,b.url)};n.bb=function(a){P(this,5,1,32,[a]);delete this.b[a];this.J==a&&zb(this)};n.Qb=function(a){if(0<a){this.J&&browser.windows.update(this.J,{drawAttention:!0});var b=this.b[a];b&&(this.M=a,b.fa||mc(this,b,!0),browser.windows.onBoundsChanged||browser.windows.get(a,this.U),Bb(this,b.B),z&&this.Da(a,!1,!0,500))}else this.M=null};n.Pb=function(a){this.Da(a.id,!0,!1,-1,a)};
n.Jb=function(a,b,c){var d=c.active;c=c.windowId;var e=d&&this.b[c];e&&(e.fa||mc(this,e));"complete"==b.status&&(a=this.a[a])&&!a.l&&(a.l=!0,d&&this.ca(c))};n.Ib=function(a){var b=this.a,c=this.u,d=a+",";this.L==a&&(this.L=null);var e=b[a];e&&this.ma(e,!0);for(var f in b)f.startsWith(d)&&this.ma(b[f],!0);for(var h in c)h.startsWith(d)&&delete c[h];delete this.h[a]};
n.Gb=function(a){var b=a.tabId;a=a.windowId;this.sa=0;this.j&&this.Z(4294967295);var c=this.b[a];c&&(Cb(this,c.B),c.B=b,(c=this.L)&&b!=c&&(this.J?browser.windows.update(this.J,{drawAttention:!0}):this.o&&this.v&&(this.L=null,window.setTimeout(browser.tabs.remove,250,c))),browser.tabs.get(b,this.U),Bb(this,b)||this.ca(a))};n.Hb=function(a,b){b=b.newWindowId;var c=this.i,d;for(d in c)(d=c[d])&&d.tabId==a&&(d.a=b);Cb(this,a,!0)};n.tb=function(a){this.J&&"idle"==a&&browser.windows.update(this.J,{focused:!0})};
n.Wa=function(a,b,c){if(a.b){var d=a.tabId;a=a.a;var e=this.b[a];this.j&&this.Z(4294967295);if(e&&e.B==d){var f=!1;b&&(e.v=b,f=!0);c&&(e.u=c,f=!0);Cb(this,d,!1,f);this.Da(a,f,!1,500)}}else a.ja&&(b=this.a[a.c])&&b.postMessage([16,null,a.$,a.ja])};n.vb=function(a,b,c){(b=kb[b])&&ic(this,b,c,a)};n.yb=function(a,b,c){0==b&&ic(this,128,c,a)};n.wb=function(a,b,c,d){this.ta=a.id;a.hb=b;a.Fa=c;a.ib=d};n.qb=function(){ic(this,255,!1)};
n.ub=function(a,b,c,d){var e=a.f;e&&(a=32,c=[e,null==c?(a|=16,-2):c],e={},e[110]=b,e[115]=d,P(this,16,1,a,c,e))};n.Rb=function(a,b,c){if(a=this.g[b]){b=[a.id,0];var d={};d[115]=c;P(this,16,1,48,b,d);a.o=!1;a.W&&X(this,a)}};n.Eb=function(a,b,c,d){P(this,19,2,0,[b,c,a.tabId,a.f],d)};function wc(a,b){if(b=a.g[b]){var c=b.i;b.o=!1;b.i=null;b.W&&X(a,b);c&&c.abort()}}n.Db=function(a,b){if(4==a.readyState){var c=[b,0],d={};200==a.status&&(d[115]=a.response);P(this,16,1,48,c,d);wc(this,b)}};
function zc(a,b){var c=a.c;if(b.s||a.h[b.tabId]||!c[-9])return 1;if(b.h)return 6;if(b.c&&c[-4])return 1;var d=b.P,e=b.S=Z(d.pathname);return c[9].test(d.hostname)||c[19].test(d.href)?1:2==(b.b&7)&&(b.K||c[-13])?d.pathname.endsWith("/")||c[21].test(d.pathname)?1:c[1].test(e)||a.l&&!c[20].test(e)?4:1:6}
function Ac(a,b){var c=!b.a;if(b.h&&c)return 3;var d=a.c,e=d[18],f=d[1],h=b.P,g=b.S,l=b.j||(h.search?null:g),k=b.c,m=Ga.includes(b.type),p=!b.K,q=!m&&e.exec(h.href);if(q){var r=e.hc,u=e.ic,A=e.jc,B=e.kc;for(e=1;e<q.length;++e)if(q[e]){r=r[--e];if(null===r)break;q=0;var v=r.includes("V")|r.includes("A")|r.includes("C");if(k&&!v&&!r.includes("S")||p&&r.includes("D"))return 1;if(r.includes("G")){var C=!0;q|="GET"==b.method}r.includes("P")&&(C=!0,q|="POST"==b.method);if(C&&!q)break;if(q=B[e]){q=q.exec(h.href);
if(!q)break;h=u[e];if(u=h.F){var I=!0;var J=q[u]}if(u=h.T){I=!0;var G=q[u]}}G||(G=Z(J)||r.includes("T")&&(I=!0,g)||A[e]);if(v)return G&&(b.S=G),k||(b.c=!0),b.a=!0,6;if(c&&(G?f.test(G):!I))return b.O=16777216,4;break}}if(!c)return 6;if(l&&(m&&d[2].test(l)||k&&d[4].test(l)))return 1;if((D||a.G)&&(b.K||d[-13])){if(k&&d[3].test(l))return 6;if((!k||a.l)&&l&&f.test(l))return b.O=8,4}return 6}
function Bc(a,b){if(b.ia)return a.ga(6,b),6;var c=b.statusCode;if(200!=c&&206!=c&&304!=c)return 1;var d=Y(b.responseHeaders,"Content-Type"),e=Y(b.responseHeaders,"Content-Disposition"),f=Cc(d).toLowerCase(),h="attachment"==Cc(e).toLowerCase();c=b.c;var g=b.v;if(b.ea=g&&!h&&"text/html"==f){if(b.g){var l=Kb(a,b);l&&(l.f=!0);a.ga(5,b)}return 1}if(c?b.s:b.a)return 1;if(a.l&&g&&h)return 4;var k,m,p,q=a.c,r=b.P,u=r.hostname,A=r.pathname;e=(d=Dc(e,"filename")||Dc(d,"name"))&&Z(d);if(d)if(e){b.u=d;var B=
p=!0}else if(!c)return 1;p||(d=A.split("/").pop(),(e=b.S||Z(d))&&e.toLowerCase()==f.split("/").pop()&&(B=!0));if(!B){var v=q[10].test(f),C=mb[f];if(C)if(C=C.split("|"),e&&C.includes(e))B=!0;else if(c?!v:!e){B=!0;var I=v;e=C[0]}!B&&e&&(h&&g?B=!0:v?B=I=!0:C||Ya(e)||(B=I=!0))}if(c){C=Pb(a,u);g=a.K[C];v=A+r.search;switch(C){case 1:if(g[111].test(v))var J=B=!0;else if(g[112].test(v))var G=!0;else if(g[115].test(v)&&"application/json"==f)var na=!0;else if(g[113].test(v)&&"application/x-www-form-urlencoded"==
f||g[114].test(v)&&"video/vnd.mpeg.dash.mpd"==f)var oa=!0;break;case 2:(u=g[111].exec(v))&&(Xa(f)||"text/html"==f)?(f=u[1]&&g[112].exec(b.port.m))&&u[1]!=f[1]||(oa=!0):g[114].test(v)?na=!0:h&&"image"==b.type&&"MP4"==e&&(m=!0);break;case 3:"M4S"==e&&(B=!0);u==g[111]&&g[112].test(A)&&Xa(f)&&(oa=!0);break;case 4:g[111].test(v)&&Xa(f)&&(na=!0);break;case 5:g[111].test(v)&&"text/html"==f&&(na=!0);break;case 6:g[111].test(v)&&(oa=!0);break;case 7:g[111].test(A)&&(na=!0)}B&&("M3U8"==e||"F4M"==e||a.Ia&&"MPD"==
e?oa=!0:"F4F"==e&&(d.endsWith("Seg1-Frag1")||d.endsWith("Seg1-Frag2")||d.includes("Seg1-Frag2_"))&&(k=!0));"ASF"==e&&((f=Y(b.responseHeaders,"Content-Length"))&&102400>=parseInt(f)&&(m=!0),"DCLK-AdSvr"==Y(b.responseHeaders,"Server")&&(m=!0))}if(m)return 1;B&&(c&&q[3].test(e)?J=!0:c&&q[4].test(e)?b.a=!0:!b.a&&q[1].test(e)&&(l=!0));if(J){var Mb,Nb;if(m=q[11])m.test(r.hostname)?J=!1:(Mb=a.a[b.tabId])&&(Nb=Mb.m)&&m.test((new URL(Nb)).hostname)&&(J=!1)}if(na)G=b.o=!0;else if(oa||k)"POST"!=b.method||b.f?
(a=new XMLHttpRequest,a.responseType=k?"blob":"text",b.i=a,G=!0):G=!1;if(!l&&!J&&!G)return 1;B&&(b.j=e);p&&(b.u=d);b.g|=G;b.O=J||G?256:16|(c?4096:0)|(I?8388608:0);return l?4:J?2:5}
n.ga=M[M.length]=function Ec(a,b,c,d,e,f){var g=b.url,l=b.b||Yb(g),k=1==(l&7),m=b.requestHeaders;if(k&&!d&&!e&&(f=Y(m,"Cookie"),null==f))return Q(g,Ec.bind(this,a,b,c,d,!0)),!0;N(f)&&(f=R(f));var p=b.id,q=b.port&&b.port.id,r=b.timeStamp,u=c?w(c.timeStamp-r):null,A=b.O,B=b.responseHeaders;e=b.X;var v=c&&c.ip;c=0;3==(v?v.length-v.replaceAll(".","").length:0)?A|=33554432:2<(v?v.length-v.replaceAll(":","").length:0)&&(A|=4194304);l&16&&(A|=2097152);"POST"==b.method&&(A|=512);4>a&&(D||d)&&(c|=1);b.g&&
b.i&&(c|=1);b.g&&5!=a&&(c|=32);b.c&&(c|=16);b.I&&(c|=8192);b.v&&(c|=b.A?2048:4096);l=[p,q,r.toFixed(),b.statusCode,l&7,a,b.tabId,b.frameId];p={};16>this.ua&&(l[2]=w(r/1E3),l[3]=w(r%1E3*1E3));p[6]=Ub(g,k&&4>a,this);p[12]=b.statusLine;p[17]=b.aa;p[4]=b.j;p[100]=b.u;p[8]=A;p[129]=u;p[122]=this.s;p[11]=Fc(m);p[13]=Fc(B);p[18]=Fc(e);b.f&&(p[14]=vc(b.f,Y(m,"Content-Type")));b.M&&(p[19]=vc(b.M,Y(e,"Content-Type")));if(null==m){a=this.u;g=b.tabId+","+b.frameId;do g=(k=a[g])&&k.c,k=k&&k.m,"about:blank"==k&&
(k=null);while(!k&&g);p[50]=k;p[51]=f;p[54]=navigator.userAgent}D&&(p[122]=Gb(this,b.proxyInfo,Y(m,"Proxy-Authorization")),p[55]=Gb(this,b.Y,Y(e,"Proxy-Authorization")));if(!b.ea||!b.A)if(b=this.a[b.tabId])p[7]=b.m;return P(this,13,1,c,l,p,d)};
n.ka=M[M.length]=function Gc(a,b,c,d,e){if(0==a)b.G=d,b.C=e,Ib(this,b);else{this.I&&lc(this,!0);d=this.G?new XMLHttpRequest:null;e=this.ga(a,b,c,d);d&&(e=(d=e&&parseInt(d.getResponseHeader("x-idm-status")))?3==d:this.ga(a,b,c));if(e)return Sa&&!c?void(b.H=!0):D?new Promise(Gc.bind(this,0,b,null)):X(this,b,!0);b.a=!0}};
function X(a,b,c){var d=a.g,e;if(N(b)){var f=b;b=f.id}else if(!(f=d[b]))return;if(c){if(f.v||f.I){var h=0<f.statusCode||!f.requestHeaders,g=Kb(a,f);g&&g.a&&f.A?browser.tabs.remove(f.tabId):y&&h&&!f.I?e={redirectUrl:"javascript:void(0)"}:z&&h?e={redirectUrl:Hc(f,g)}:Ua&&h&&(e={redirectUrl:a.C||Hc(f,g)})}e||(e={cancel:!0});f.H=!0}(a=f.G)&&void 0!==c&&(f.G=f.C=null,a(e||{}));if(c=f.C)f.G=f.C=null,c();if(f.i||f.o)return f.W=!0,e;delete d[b];z&&delete d[f.requestId];f.V&&delete d[f.V];return e}
n.mb=function(a){(this.l||a.byExtensionId)&&!this.Aa&&this.c[-9]&&Yb(a.finalUrl||a.url,!0)&&(this.S[a.id]=a,browser.downloads.pause(a.id,O))};
n.nb=function(a,b){var c=a.id,d=this.S;if(!d[c])return!1;var e=this.c,f=a.finalUrl||(a.finalUrl=a.url),h=new URL(f),g=a.b=Yb(f,!0),l=a.j=Z(a.filename||h.pathname);if(!(a.h=this.ra)&&!this.l&&(!e[1].test(l)||e[9].test(h.hostname)||e[19].test(h.href)))return uc(this,c);a.$b=b;d[c]=a;if(1==g){if(!a.referrer){b=this.i;c=this.b;for(var k in b)if(d=b[k],d.m==f&&(a.referrer=d.u,(e=c[d.a])&&e.B==d.tabId))break}var m;Q(f,k=S());a.url==f||Q(a.url,m=S());T(this.Ua,this,a,k,m);return a.Oa=!0}return this.Ua(a)};
n.Ua=function(a,b,c){var d=Date.now();d=[a.id,0,w(d/1E3),w(d%1E3*1E3),a.b,2];var e={};e[6]=Ub(a.finalUrl);e[4]=a.j;e[103]=a.totalBytes||null;e[100]=a.filename||null;e[127]=a.mime||null;e[8]=a.h?2048:0;e[50]=a.referrer||null;e[51]=R(b);e[54]=navigator.userAgent;e[122]=this.s;a.finalUrl!=a.url&&(e[17]=Ub(a.url),e[56]=R(c));return P(this,13,1,129,d,e)||uc(this,a.id)};
function uc(a,b,c){var d=a.S[b];if(d){if(c)return browser.downloads.cancel(b,O),!0;d.Oa&&(d.Oa=!1,d.$b());browser.downloads.resume(b,O);delete a.S[b]}return!1}n.lb=function(a){if(!(0>a.tabId||a.initiator==Pa||this.pa||a.url.startsWith(Na)&&a.type.endsWith("_frame")&&(Ua||z)||a.url.startsWith(Oa)&&"main_frame"==a.type))return{cancel:!0}};
n.Kb=function(a){var b=new URL(a.url);if(b.search.startsWith("?d=")){var c=this.a[a.tabId];this.ha("idmreg:"+b.href.substr(b.protocol.length),null,c&&c.m);X(this,a.requestId);(b=Kb(this,a))&&b.a&&"main_frame"==a.type&&browser.tabs.remove(a.tabId);return{redirectUrl:Na+"register=1"}}};
n.$a=function(a){var b=a.type,c=a.tabId,d=a.frameId;if(!(pa&&!Ia.includes(b)||0>c&&0==d)){var e=a.url,f=a.method,h=Yb(e);if(h&&("GET"==f||"POST"==f)&&e!=this.C){var g=a.id=z?String(this.Xb++):a.requestId;g=this.g[g];var l=this.Aa,k="POST"==f,m="image"==b,p=y&&0>c&&"other"==b,q=!p&&0>c&&0>d,r=0<c&&b.endsWith("_frame");if((f=q?null:this.a[c+","+d])||r||q||p||g){D&&k&&g&&db(g.statusCode)&&(a.method="GET",k=!1);r&&Jb(this,a,!1);if(!l&&k&&a.requestBody){k=a.requestBody;var u=k.raw;if(u)for(var A=0;A<u.length&&
(u[A].bytes||(u=null));A++);if(!(u||k.formData||y&&k.error))return}if((k=this.ta)&&(u=f?f.id==k&&f:this.i[k])&&e==u.Fa){p=u.hb;if(k=u.ib)a.u=k,a.j=Z(k);f||(f=u);this.ta=null}k=new URL(e);k.hash="";a.P=k;a.b=h;a.h=this.ra;a.s=l;a.A=r&&"main_frame"==b;a.v=r;a.I=p;a.da=q;a.c=q||Ha.includes(b);a.a=m;a.g=this.La.test(e);a.f=a.requestBody;a.port=f;a.K=h&8||(D?a.proxyInfo&&"https"==a.proxyInfo.type:this.ea[h]);0>c&&(a.tabId=null);0>d&&(a.frameId=null);g&&(a.id=g.id,a.port=f=g.port,a.h=g.h,a.s=g.s,a.aa=g.aa||
g.url,a.X=g.X||g.requestHeaders,a.M=g.M||g.f,D&&(a.Y=g.Y||g.proxyInfo));if(a.c&&!m){b=this.V;for(c=b.Wb;30<=c.length;)delete b[c.shift()];b[e]=f;c.push(e)}switch(a.l=zc(this,a)){case 1:a.a=!0;case 6:Ib(this,a);break;case 4:return this.ka(1,a)}}}}};
n.Lb=function(a){var b=this.g[a.requestId];if(b){var c=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.H){if(b.da&&!b.port&&(a=Y(c,"Referer")))for(var d of V(this.i))if(d.m==a){b.port=d;break}D&&b.proxyInfo&&Gb(this,b.proxyInfo,Y(c,"Proxy-Authorization"),!0);if("POST"==b.method&&(!b.f||b.f.error&&0<Y(c,"Content-Length")))return X(this,b);switch(b.l=Ac(this,b)){case 1:b.a=!0;break;case 4:return this.ka(1,b);case 3:return this.ka(3,b)}if(b.port&&b.port.i&&"xmlhttprequest"==b.type)for(d=
0;d<c.length;d++)if(a=c[d],"accept"==a.name.toLowerCase()&&a.value.startsWith("x-idm-request-id/")){var e=a.value,f=e.indexOf(",");0>f&&(f=void 0);var h=e.slice(17,f);e=f&&e.slice(++f).trim();b.V=h;this.g[h]=b;e?a.value=e:c.splice(d--,1);return{requestHeaders:c}}}}else if(0>a.tabId&&"xmlhttprequest"==a.type&&(a.initiator?a.initiator==Pa:a.originUrl?a.originUrl==Qa:1)){b=a.requestHeaders;c={};e=!1;for(d=0;d<b.length;d++)a=b[d],f=a.name.toLowerCase(),f.startsWith("x-idm-")?c[f.substr(6)]=e=!0:"origin"==
f&&a.value==Pa&&(c[f]=e=!0);if(e){for(d=0;d<b.length;d++)a=b[d],f=a.name.toLowerCase(),c[f]?b.splice(d--,1):f.startsWith("x-idm-")&&(a.name=a.name.substr(6));return{requestHeaders:b}}}};
n.Nb=function(a){var b=this.g[a.requestId];if(b){var c=b.statusLine=a.statusLine,d=b.statusCode=a.statusCode||parseInt(c.split(" ",2).pop());if(b.H||204==d&&c.includes(" IDM "))return X(this,b,!0);c=b.responseHeaders=a.responseHeaders;b.ia=cb(d);if("image"==b.type&&(d=Y(c,"Content-Type"))&&d.toLowerCase().startsWith("image"))return X(this,b);"quic"==Y(c,"Client-Protocol")?b.b|=16:(d=Y(c,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=Y(c,"Transfer-Encoding")&&(b.b|=16);switch(b.l=Bc(this,
b)){case 1:return X(this,b);case 4:return this.ka(2,b,a);case 3:return this.ka(3,b,a)}if(b.o)return c.push({name:"x-idm-request-id",value:b.id.toString()}),{responseHeaders:c}}};n.Ob=function(a){var b=this.g[a.requestId];if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){var c=Kb(this,a);c&&(c.m=a.url,c.aa=c.j)}b&&(2==b.l?this.ga(4,b,a):5==b.l&&this.ga(5,b,a),X(this,b))};n.Mb=function(a){X(this,a.requestId)};
n.Yb=M[M.length]=function Ic(a,b,c,d,e){a?(this.Sa=N(b)?b.version:"",this.Ka=e,this.v=D&&N(c)?!!c.consent:!0,this.Ja=D?N(d)&&d.value==Pa:!0,this.za()):(browser.storage.local.get("version",b=S()),D&&browser.storage.local.get("consent",c=S()),D&&browser.cookies.get({url:ta.homepage_url,name:"idmmzcc3_uri"},d=S()),(D?1124073472<=E:z?1073741824<=E:1)&&browser.extension.isAllowedIncognitoAccess(e=S()),T(Ic,this,!0,b,c,d,e))};
function Qb(a){function b(k){k&&(this.L=k.id)}a.L&&(browser.tabs.remove(a.L),a.L=null);if(a.Ta||!a.v){var c=!a.o,d=!a.Ka,e=!a.v,f=a.va,h=a.da,g=a.Sa,l=a.qa;c||(a.Ta=!1,l!=g&&(l&&browser.storage.local.set({version:l}),D&&browser.cookies.set({url:ta.homepage_url,name:"idmmzcc3_uri",value:Pa,expirationDate:2147483647})));if(null!=g&&(e=!1,a.v=!0,l!=g?h&&!f&&!e:!e))return;l=Oa+"current="+escape(l);g&&(l+="&previous="+escape(g));h&&(l+="&manager="+(h?[h>>24&255,h>>16&255,h>>8&255,h&255].join("."):""));
c&&(l+="&error=1");d&&(l+="&incognito=1");f&&(l+="&update=1");e&&(l+="&consent=1");D&&(l+="&mzffox=1");ja&&(l+="&opera=1");if(z||ia)l+="&msedge=1";if(e&&!c){browser.idle&&a.D(5,browser.idle.onStateChanged,a.tb)&&browser.idle.setDetectionInterval(15);browser.windows.create({type:"popup",width:Math.min(Math.round(.85*screen.availWidth),1100),height:Math.min(Math.round(.85*screen.availHeight),900),url:l},k.bind(a));function k(m){m&&m.id?(this.J=m.id,this.L=m.tabs[0].id,L(this,!1,null,!0)):zb(this)}}else browser.tabs.create({url:l},
b.bind(a))}}function qc(a,b,c){null==b&&(b=(b=bb(c[13]))?b[1]<<24|b[2]<<16|b[3]<<8:0);a.da=b||0}function rc(a,b){var c=a.va=103089920>a.da,d=103219200>a.da;c?a.I=null:a.I=d?6E4*w(120*x()+60)*(b?1:2)+Date.now():-1}function lc(a,b){if(b||a.I<Date.now()){a.I=6E4*w(240*x()+120)+Date.now();var c="xup://"+x().toString(36).substr(2);b?a.ha(c):window.setTimeout(a.ha,w(5E3*x()+5E3),c)}}
function cc(a,b){b=browser.i18n.getMessage(b);D?browser.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(b)+'")); true;'},O):window.alert(b)}n.D=function(a,b,c){if(null==b)return!1;var d=ea(arguments);if(D||z)d[2]=function(){return c.apply(null,arguments)};this.Ea.push(d);b.addListener.apply(b,d.slice(2));return!0};
n.ya=function(){for(var a=arguments.length?ea(arguments):null,b=this.Ea,c=0;c<b.length;c++)if(!a||a.includes(b[c][0])){var d=b.splice(c--,1).pop(),e=d.splice(0,2).pop();z&&d.splice(1);e.removeListener.apply(e,d)}};function S(){function a(b){browser.runtime.lastError;a.a?a.a(b):a.c=b;a.b=!0}return a}S.prototype=Object.create(Function.prototype);function $b(){var a=[];Object.setPrototypeOf(a,$b.prototype);return a}$b.prototype=Object.create(Array.prototype);
function T(a,b,c){if(this instanceof T){c instanceof Array||(c=ea(arguments,2));for(var d=0,e=0,f=Function.prototype.bind.bind(this.g,this),h=0;h<c.length;h++){var g=c[h];if(g instanceof Function)g.b?(c[h]=g.c,e++):(g.a=f(h,null),d++);else if(g instanceof $b)for(var l=0;l<g.length;l++){var k=g[l];k.b?(g[l]=k.c,e++):(k.a=f(h,l),d++)}}d?(this.c=a,this.f=b,this.a=c,this.b=d):e&&(this.h=e,a.apply(b,c))}else return d=new T(a,b,ea(arguments,2)),d.b||d.h}
T.prototype.g=function(a,b,c){var d=this.a;if(null===b)for(var e=2;e<arguments.length;e++)d[a++]=arguments[e];else d[a][b]=c;0==--this.b&&(this.c.apply(this.f,d),delete this.c,delete this.f,delete this.a)};function va(a){return browser.i18n.getMessage(a)||a}function Ub(a,b,c){var d=a.lastIndexOf("#");d>a.indexOf("?")&&"!"!=a[d+1]&&(a=a.substr(0,d));b&&!Za(a)&&(c.va?a="idm0x00000001"+a:a.startsWith("xup")&&(a="idm0x00000002"+a.slice(3)));return a}
function Hc(a,b){var c=a.port;b=b&&!b.h;var d=new URL(c&&c.m||a.url);z&&(c&&a.url==c.Fa||(b=!1));return Na+(b?"back=1":"host="+d.hostname)}function Q(a,b){z&&a.startsWith("ftp:")?b([]):(a={url:a},ma&&(a.firstPartyDomain=null),browser.cookies.getAll(a,b))}function R(a){var b="";if(a&&a.length)for(var c=0;c<a.length;c++)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}
function Fc(a){if(!a||!a.length)return null;var b=[],c;for(c of a)b.push(c.name,": "),null!=c.value?b.push(c.value):c.binaryValue&&b.push(new Uint8Array(c.binaryValue)),b.push("\r\n");return b}function Y(a,b){if(!a)return null;b=b.toLowerCase();for(var c of a)if(c.name.toLowerCase()==b){if(null!=c.value)return c.value;if(c.binaryValue)return String.fromCharCode.apply(null,c.binaryValue)}return null}
function Dc(a,b){if(!a)return null;a=a.split(";");for(b=b.toLowerCase();a.length;){var c=a.shift(),d=c.indexOf("=");if(0<d){var e=c.slice(0,d).trim().toLowerCase(),f=e.endsWith("*");if(f)e=e.slice(0,-1).trimRight();else if(g)continue;if(e==b){c=c.substr(d+1).trim();d=c.length-1;if('"'==c[0]?'"'==c[d]:"'"==c[0]&&"'"==c[d])c=c.slice(1,d);if(f&&c.includes("'")){if(c=c.split("'",3),f=c.shift().toLowerCase(),(d="utf-8"==f||"utf8"==f)||!g){var h=unescape(c.pop());var g=f;if(d)break}}else h=unescape(c)}}else 0>
d&&null==h&&c.trim().toLowerCase()==b&&(h="")}return h}function Cc(a){const b=/[;,]/;return a&&(a=a.split(b,1).shift().trim())&&!a.includes("=")&&unescape(a)||""}
function vc(a,b){var c,d=[];if(c=a.raw)for(var e of c)if(e.bytes)d.push(Jc(e.bytes));else return null;else if(a=a.formData)if((c=Cc(b).toLowerCase())&&"application/x-www-form-urlencoded"!=c)if("multipart/form-data"==c){(b=Dc(b,"boundary"))||(b="----WebKitFormBoundary"+x().toString(36).substr(2));for(f in a)for(h of a[f])h instanceof ArrayBuffer&&(h=Jc(h)),d.push("--",b,'\r\nContent-Disposition: form-data; name="',f,'"\r\n\r\n',h||"","\r\n");d.push("--",b,"--\r\n")}else return null;else for(var f in a){b=
encodeURIComponent(f).replaceAll("%20","+");for(var h of a[f])h=h instanceof ArrayBuffer?escape(Jc(h)):null==h?"":encodeURIComponent(h),d.length&&d.push("&"),d.push(b,"=",h&&h.replaceAll("%20","+"))}else return null;return d.join("")}function Z(a){return(a=ab(a))?a.pop().toUpperCase():""}function Yb(a,b){a=a.split(":",1).shift().toLowerCase();a=lb[a]||0;return b?a&7:a}function ob(a){for(var b=a.length,c=b,d=0;d<c;){var e=a.charCodeAt(d++);128<=e&&(2048<=e?(b+=2,e-55296&56320||d++):b++)}return b}
function Kc(a,b,c,d){browser.runtime.lastError;if(!a){y&&Lc();navigator.userAgentData?navigator.userAgentData.getHighEntropyValues(["uaFullVersion"]).then(b=S()):browser.runtime.getBrowserInfo&&browser.runtime.getBrowserInfo(b=S());try{browser.privacy&&browser.privacy.websites.firstPartyIsolate.get({},c=S())}catch(h){}y&&browser.management.get("clhiejnehegdfknplplojohghjaklbae",d=S());return T(Kc,null,!0,b,c,d)}var e=navigator.userAgent;a=e.match(/\b(?!(?:Safari|Chrome|Gecko)\/)\w+\/(\d+)(?:.(\d+))?(?:.(\d+))?(?:.(\d+))?\b(?!.*[()])/);
la=(e=D?a:e.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/))?e[0]:"UNKNOWN/0.0";F=a?a[0]:la;e&&e.shift();if(N(b))if(a=b.uaFullVersion)e=a.split(/\D+/),la="Chrome/"+a;else if(a=b.version)e=a.split(/\D+/),53<=e[0]&&(la=F=b.name+"/"+a);e&&(E=e[0]<<24|e[1]<<22|e[2]<<8|e[3]);y&&navigator.brave&&(F=F.replace("Chrome/","Brave/"));y&&d&&(qa=!0,F=F&&F.replace("Chrome/","Epic/"));D&&N(c)&&(ma=c.value);D&&939524096>E&&(Ua=!0);b=browser.webRequest.ResourceType;if(b){if(b.MEDIA){Ia.push("media");Ha.push("media");
var f=!0}if(b.OBJECT_SUBREQUEST||(pa=D&&922746880>E))Ia.push("object_subrequest"),Ha.push("object_subrequest")}y&&(f||Ha.push("other"));D&&922746880>E&&Ha.push("other");new K;Mc(1,"debug.js");Mc(2,"document.js")}
function Lc(){function a(d){browser.runtime.lastError;N(d)&&d.enabled&&browser.management.setEnabled(d.id,!1)}function b(d){browser.runtime.lastError;N(d)&&d.enabled&&browser.management.setEnabled(c||browser.runtime.id,!1)}var c=ia&&"llbjbkhnmlidjebalopleeepgdfgcpec"==browser.runtime.id&&"ngpampappnmepgilojfohadhhmbhlaek";y&&browser.management.get("jeaohhlajejodfjadcponpnjgkiikocn",a);ia&&browser.management.get(c||"llbjbkhnmlidjebalopleeepgdfgcpec",b)}
function Mc(a,b,c){c?4==c.readyState&&(eb[a]=btoa(c.responseText)):(c=new XMLHttpRequest,c.responseType="text",c.onreadystatechange=Mc.bind(null,a,b,c),c.open("GET",browser.runtime.getURL(b)),c.send())}
function W(a,b,c,d){if(b=b[c]||void 0)try{b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\."),b=1==d?b.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):b.replace(/\?/g,".").replace(/\*/g,".*?"),2==d&&(b=b.replace(/~/g,"(?:\\b[^.]+\\.)?")),b=RegExp("^(?:"+b+")$",1==d?"":"i")}catch(e){b=null}a[c]=b||Ea}
function sc(a,b,c,d,e){b=b[c];var f=[],h=[],g=[],l=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(d){for(var k=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");k.length;){var m=k.shift();f.push($a(m)?m:null);h.push(k.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(e){k=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");m=/<([A-Z]):(.*?)>/g;for(var p={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"},q,r=0;k.length;++r)if(q=k.shift()){for(var u={},A=["^"],B="",v,C=1;v=m.exec(q);++C)u[v[1]]=C++,B=RegExp.rightContext,A.push(RegExp.leftContext,"(",v[2].replace(/\*/g,p[v[1]]||".%%?"),")");A.push(B,"$");g[r]=u;l[r]=RegExp(A.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(m,"(?:$2)")}b=b.replace(/\*/g,".%%?").replace(/%%/g,"*");b=d||e?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(I){b=
null}a[c]=b||(b=/(?!)/);d&&(b.hc=f,b.jc=h);e&&(b.ic=g,b.kc=l)}function Wb(a){return N(a)?a.source.replaceAll("\\/","/"):a}function pc(a,b){b&&browser.runtime.lastError||browser.permissions.request({permissions:[a]},b)}function O(a){browser.runtime.lastError;a;!0}
URL.prototype.a="searchParams"in URL.prototype?function(a){return this.searchParams.get(a)}:function Nc(a){var c=Nc.cache||(Nc.cache={});return(a=(c[a]||(c[a]=new RegExp("[?&]"+escape(a)+"\\b(?:=([^&]*))?"))).exec(this.search))&&unescape(a[1]||"")};const Vb=Function.bind.bind(function(a){return this[a]}),tc=Function.bind.bind(function(a){return a&&a[this]}),Jc=window.TextDecoder?TextDecoder.prototype.decode.bind(new TextDecoder("ascii")):function(){return""};var N=Object.isExtensible;
try{N(null)}catch(a){N=function(b){return b instanceof Object}}var V=Object.values;V||(V=function(a){return Object.keys(a).map(Vb(a))});Array.prototype.fill||(Array.prototype.fill=function(a){for(var b=this.length;b--;this[b]=a);return this});String.prototype.replaceAll||(String.prototype.replaceAll=function(a,b){return this.split(a).join(b)});
const Db=[[!0,-11,"menu_download_link","link,image,video",K.prototype.Ba],[!0,-11,"menu_download_link","page,frame,editable",K.prototype.Ba,La],[!0,-11,"menu_download_selected","selection",K.prototype.Ha],[!0,-12,"menu_download_all","page,frame,editable",K.prototype.Ha],[y,-11,"menu_download_item","link",K.prototype.Ba,["chrome://downloads/*"]]];M.splice(0);Kc();
